### ISSUE TITLE
#605 共通 “受难者”

### ISSUE THREAD

**Issue by elementary-particle** [elementary-particle/my-moyu-text#1]
### 原文

>やさしい心の持ち主は、われにもあらず受難者となる

### 原译

>心地善良的人，是不会沦为我们这种受难者的

### 意见

>其大意为，内心良善者，因其总对他人的痛苦感同身受，因而会不自觉地总在受苦受难。原句乃用于歌颂如耶稣般善良的人们和描述他们所遇见的内心困境的。

**Comment by Linrop** [comment]
内心善良者，总是迫不得已地沦为苦难者

**Comment by Linrop** [comment]
联系语境做出调整

**Comment by mitukichimei** [comment]
已修改
