### ISSUE TITLE
#588 共通 “绝无仅有的东西”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#10]
### 原文

>だが……たったひとつだけ手に入れたものがある。

### 原译

>不过……手头上仍有一样绝无仅有的东西。

### 意见

>“但是……我手中还剩下唯一一件东西”
>这里只是说少，倒也不是往“珍稀、少见”那方向靠。
>“绝无仅有”就是形容少见耳，百科查得到。

**Comment by Linrop** [comment]
议：但是……只有这件事
我不清楚原文所以不知道这么翻合不合适

**Comment by mitukichimei** [comment]
已修改
