### ISSUE TITLE
#15365 小黑线 “真白，拯救这个世界”

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#100]
原文：
ましろにとってこの世界を救うということは、自身を愛してくれる多くのものたちから、自ら進んで憎まれようとする行為そのものだ。
原译：
真白，拯救这个世界，正是那些爱着自己的人们主动去憎恨自己的行为
意见：
对真白而言，拯救这个世界，就是让那些爱着自己的人主动去憎恨自己

**Comment by Sept9th** [comment]
这里是维护人员，请问您是否在翻译群或是测试群中。
如果是，希望在群内进行id认领。
如果不是，请带上您现在使用的 github id 联系我（qq.3150535868），我向您提供调试补丁和情况说明。
