### ISSUE TITLE
#604 共通 “首先得紧紧握住”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#11]
### 原文

>それが俺、奏大雅の成すべきことだろうと強く信じる。
>地面を蹴り、振り返らず――坂道を駆け下りた。
>この空っぽの手のひらが、まず最初に手に入れたものをしっかりと握り締めたまま。

### 原译

（最后一句）
>这只空荡荡的手，首先得紧紧握住最初得到的东西。

### 意见

>问题是第三句，“首先得”是错的。“まず最初に”是一个整体，是说一开始就有的东西。
>然后是“まま”的意思丢了，看前面两句，这三句是连贯的，意思是“握着仅有的宝物启程”，这个意思不能丢，丢了就断了逻辑联系。

**Comment by Linrop** [comment]
这只空荡荡的手，还紧握着最初得到的东西
