### ISSUE TITLE
#418-426 共通 “回想起许许多多的事情”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#12]
### 原文

>色々なことを思い出してしまう。
>…………
>色々だ。

### 原译

>回想起了许许多多的事情。
>…………
>发生了各种各样的事情。

### 意见

>这一段比较长，我就只放头尾了，应该看得懂。原文亦如是。
>这里是一个连续的逻辑，先是感慨“到这之后，发生了太多太多”——之后总结感慨，又一句“真是太多了啊”，也就是说，头尾的“色々”是呼应的，而后文的那个很简短，就是这个原因。图中翻译并未把握住，而是将这两句当成了独立的意思，有误。

**Comment by Linrop** [comment]
单看这两句不才认为：各种各样的事涌现脑海……太多了
