### ISSUE TITLE
#305 “不知道这是谁的名言”

### ISSUE THREAD

**Issue by mitukichimei** [elementary-particle/my-moyu-text#15]
### 原文

>『本棚を見ればその人物がどのような人生を送ってきたかわかる』――とは誰の言葉だっただろうか。

### 原译

>『只要看看书架就可以知道一个人过着怎样的人生』——不知道这是谁的名言。

**Comment by Sept9th** [comment]
尝试寻找了一下出处，并未找到准确的指向，仅得到了以下两片内容。
本棚は、その人を映し出す鏡です。（作者不详，来源不详）
了解一个人就看他读什么书，了解一个国家就看它的图书馆都有什么书。（疑似塞谬尔•斯迈尔斯所说，原文不详，来源存疑）
仅提供参考。

**Comment by Linrop** [comment]
确实是个名言，但作者不详，保留原意即可

**Comment by mitukichimei** [comment]
已修改
