### ISSUE TITLE
#1999-#2001

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#18]
#1999
#2000
#2001
おお〜。白玉に抹茶のムースにチョコレートの飾りつけ。うん、美味しそうだ
手を合わる。
それでは、遠慮なくいただきま――
哦哦！在白玉团子上点缀着抹茶和巧克力，看上非常美味。
我合起双手。
那，我就不客气地开动了——

可能的修改：
哦哦！缀以巧克力的抹茶慕斯配上白玉团子，看上去非常美味。
//因为点单时声明“抹茶帕菲”，所以认为这里的主体是抹茶のムース，慕斯译丢了。白玉团子可能是作为辅料出现而非主体。
（试着想象一块慕斯上面洒了一些巧克力碎屑和糯米团子的场景）
我双手合十。
//合起双手可能有别的意图，但双手合十便能直接让人联想到“我开动了”的场景。
那，我就不客气了——
//中文语境里不客气包含后面开动的意图，认为可以省略。

**Comment by mitukichimei** [comment]
虽然但是，いただきます的时候好像双手不是合十吧？

**Comment by Linrop** [comment]
哦哦！缀以巧克力的抹茶慕斯配上白玉团子，嗯，好好吃的样子
双手一合
那，我就不客气了——
语气更加偏向粗犷的男性用语
