### ISSUE TITLE
#12534 小黑线 “过路魔”（文本不统一）

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#19]
在决定的结婚典礼的那个晚上，那个孩子被过路魔刺伤，离开了这个世界。
名词值得斟酌一下

**Comment by lxuiii** [comment]
12534 結婚式の日取りを決めたその夜に、あの子は通り魔に刺され、この世を去った。

**Comment by Akatsukiketu** [comment]
通り魔就是随机杀人犯 直译就可以了吧。

**Comment by xiyangyang0hao** [comment]
目前看是日本一典故，意思是无差别杀人犯，翻译成过路魔也行，后面注释一下就好了（）
