### ISSUE TITLE
#587 共通 "嘴巴里说出的话语和笑"

### ISSUE THREAD

**Issue by gGarywu** [elementary-particle/my-moyu-text#2]
### 原文

>口に出すと笑えるくらい、なにもない

### 原译

>除了从嘴巴里说出的话语和笑之外，什么都没有。

### 意见

>“说出来都想笑”

**Comment by elementary-particle** [comment]
？请选择正确的tag，提交相应的错误

**Comment by gGarywu** [comment]
此句位于编号587

**Comment by Linrop** [comment]
议：除了说两句和笑两声之外，一无所有

**Comment by mitukichimei** [comment]
已修改，暂定为：一无所有到说出来都会让人发笑的程度
