### ISSUE TITLE
#15493 小黑线 大雅向真白告白

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#20]
原文：彼ら("夜のイキモノ")は君を、母親として愛していたのだろけれど...、....お母さんじゃいやなんだ
原译：他们（“夜晚的生物”）是作为母亲爱着你的吧......我讨厌作为母亲
意见：他们也许是把你当作母亲来爱，但我不想把你当作母亲（来爱）

**Comment by Linrop** [comment]
对的，这一段我翻译的，我的锅
