### ISSUE TITLE
#13310 小黑线 过路魔2 （文本不统一）

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#21]
13310 周囲に集まる人たちの言葉を集めるてみると、どうやら女の人は通り魔に刺されてしまったようだ。
       从周围人群的话来看，女人好像被过过路的歹徒刺伤了。
       
       不统一

**Comment by Sept9th** [comment]
这个称呼可能出自民间传说妖怪“通り悪魔”，在中文的新闻报道里，一般会使用“随机杀人狂”来称呼此类犯人。

**Comment by Sept9th** [comment]
顺便这里的原译多了一个“过”，疑似笔误。
