### ISSUE TITLE
#13432 小黑线 过路魔 3（文风不统一）

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#22]
愛する人と同じようにして、通り魔に、命を軽率に奪われてしまった女の人だ。
       和所爱的人一样，被过路的歹徒轻率夺去生命的女人。

**Comment by Linrop** [comment]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/82795940/189816545-4a220805-279d-49c0-bd1a-1b3713720763.png">

**Comment by Linrop** [comment]
故议：过路煞神
<img width="298" alt="image" src="https://user-images.githubusercontent.com/82795940/189816654-e99674d4-69d9-4886-b5fd-1f0a53ba1d99.png">
