### ISSUE TITLE
#14249 小黑线-语句不通顺

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#23]
14249 ……自分たちを追い詰め、なぶり、都合のいいように言いくるめ、まるで子どもらのほうにこそ咎があると言わんばかりに軽 んじて……
       ……把自己逼到绝境，装模作样，随意地胡言乱语，简直就像是在说孩子们才罪魁祸首似的……

**Comment by Linrop** [comment]
……自我欺瞒，逆来顺受，总是简直就好像是孩子咎由自取一般轻描淡写……
