### ISSUE TITLE
#14277 小黑线 “把自己当成人看待的大人”

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#24]
14277 ……子ども達は、ただそれだけで、自分のことをまるで人間とも扱わないような大人にも、苦しいばかりの下らない現実にも 負けず、倒れず、泣かずにいられたのに
       ……孩子们光是这样，就不会输给那些把自己当成人看待的大人，不会输给只有痛苦不堪的现实，也不会倒下，不会哭泣。
 
那些把自己不当成人看待的大人

**Comment by Linrop** [comment]
改为：不把自己当人养的大人

**Comment by Linrop** [comment]
原译不知所云

**Comment by Sept9th** [comment]
“只有痛苦不堪的现实”也不合适，“痛苦不堪”用以修饰“现实”，“只有现实”是说不通的。可能可以改为“不会输给除了痛苦（以外）别无他物的现实”

**Comment by Linrop** [comment]
有没有可能再缩短点，这修饰语太沉了

**Comment by Sept9th** [comment]
主要是想保留”只有“，否则可以直接写成”不会输给痛苦不堪的现实“。毕竟”现实“已经”痛苦不堪“了，就算再有别的元素也不会改变它的属性。

**Comment by Akatsukiketu** [comment]
> 主要是想保留”只有“，否则可以直接写成”不会输给痛苦不堪的现实“。毕竟”现实“已经”痛苦不堪“了，就算再有别的元素也不会改变它的属性。

无聊乏味 满是伤痛的现实如何
