### ISSUE TITLE
#14298 小黑线 “对孩子们强加这不是人的待遇”

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#25]
14298 そういう大人たちだから、元来、子ども達に人とも思えぬ扱いを強いていたのだ――これは自分たちへの復讐なのだと、大人 達は身勝手に思い込んだ。
       正因为是这样的大人们，本来就对孩子们强加这不是人的待遇——这是对自己的复仇，大人们任性地这样认为。

本来就对孩子们强加着不是人的待遇

**Comment by Linrop** [comment]
正是因为是这样的大人，所以他们才将自己认为非人的待遇强加于孩子们——他们自以为这是对自己的报复
