### ISSUE TITLE
#14595 注定要被充满仇恨吞噬

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#26]
原文：
それらはすべて、いっぱいの憎悪に呑まれ、消えゆくのが運命なのかもしれないけれど……
原译：
也许所有这些都注定要被充满仇恨吞噬，然后消失……
可能的修改方式：
也许所有这些都注定要被数不尽的仇恨吞噬，然后消失……

**Comment by hiyouga** [comment]
【个人意见】
尽管那一切或许都会被几欲迸涌的仇恨所吞噬，随之迎来灰飞烟灭的命运……
尽管那一切都注定会被几欲迸涌的仇恨所吞噬，随即消逝无踪……

**Comment by Linrop** [comment]
也许、那一切注定要消失、注定要被无尽的仇恨所吞噬……
建议更换语序，把仇恨后置

**Comment by hiyouga** [comment]
> 也许、那一切注定要消失、注定要被无尽的仇恨所吞噬…… 建议更换语序，把仇恨后置

吞噬后才能消失，逻辑结构顺序不能改。
