### ISSUE TITLE
#2070共通：发生了或没发生

### ISSUE THREAD

**Issue by mitukichimei** [elementary-particle/my-moyu-text#27]

**Comment by mitukichimei** [comment]
原文：色々あったりなかったりしたけれど、おおむね成功だったよねと。
原译：像是在说“虽然发生了各种各样的事，但基本上是成功了”。
原文含有发生或没发生一意，是否需要修改细化。

**Comment by mitukichimei** [comment]
暂定：像是在说“虽然发生了很多事，也有很多事没发生，但基本上是成功了”。

**Comment by mitukichimei** [comment]
修正：像是在说删去

**Comment by mitukichimei** [comment]
暂定：虽然发生了很多事，也有很多事没能发生，但基本上是成功了。
删除像是在说，原文并无此意，同时结合下文可得知这句就是千和说出来的。

**Comment by Linrop** [comment]
虽然问题不少，但总归是成功了

**Comment by Linrop** [comment]
我不了解语境
