### ISSUE TITLE
#9437 做到不被大家讨厌的那个我吗？

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#28]
#9437
原文：
……私はちゃんと、みんなに嫌われないような私で、いられるのかな
原译：
……我有好好的，做到不被大家讨厌的那个我吗？
可能的修改：
……我有好好的，成为不被大家讨厌的那个我吗？

**Comment by Linrop** [comment]
我成为了那个、不被大家讨厌的、我吗？
建议不要直译出ちゃんと
