### ISSUE TITLE
#9439 和

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#29]
原文：
……こんなのは“[あの子|ぬいぐるみ]”に比べたらほんの些細なものだよね。悩み――と呼んでしまうのもおこがましいのかもしれない
原译：
……和[那个孩子|布偶比起来，这些都是微不足道的。称之为烦恼或许也太狂妄了。

回括号没了，在游玩中这句无法显示。

**Comment by Linrop** [comment]
译文没啥问题
