### ISSUE TITLE
#332/333 共通 “钱不会增加”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#3]
### 原文

>我ながらわびしい。
>独り言だって増えるというもの。

### 原译

>我可真穷啊。
>就算自言自语，钱也不会增加。

### 意见

>第一，第一句中“わびしい”更多应偏向于表达“落魄、寒酸”的意思，而非单指“穷”的现状。
>第二，第二句完全错译。正确应为“自言自语的时候也多了起来。”
>意思大致是说，大雅此时一穷二白，这种窘境使他一个人唉声叹气的次数多了起来。

**Comment by Linrop** [comment]
？原译不知所云，议：我好寂寞啊，甚至都开始自言自语了

**Comment by mitukichimei** [comment]
已修改
