### ISSUE TITLE
#14729  #14730 小黑线 看错行翻译出错

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#30]
14729 そんな俺の沈黙が、更にましろをひとりぼっちにさせてしまうことくらい、言葉ではなく心で理解できていた……はずなのに 。
       我可以理解，我的沉默会让真白更加孤独，不是在言语上，而是在心里。

 14730 君をひとりになんてしないから――そう言う代わりに、あの子の手を再び掴むべきだったのに。
       我的沉默会让真白更加孤独的，不是在语言上，而是在内心里，我能理解……明明应该理解的。

**Comment by hiyouga** [comment]
【改进建议】

我早该发自内心地体会到……像那样沉默不言只会让真白愈发地感到孤独。

我不会让你孤身一人——我当初明明应该用行动代替言语，再次握住她那只手的。

**Comment by Linrop** [comment]
第二句建议交换语序改为，我当时明明应该用实际行动说——我不会让你孤身一人，握住那孩子的手。
我改的不好，不知道语言怎么再调整

**Comment by Akatsukiketu** [comment]
> 【改进建议】
> 
> 我早该发自内心地体会到……像那样沉默不言只会让真白愈发地感到孤独。
> 
> 我不会让你孤身一人——我当初明明应该用行动代替言语，再次握住她那只手的。

たはずなのに、应该是明明已经。。。的意思，而はずだったのに才是早该的意思。我觉得用行动代替可以意译下。
我明明知道我的沉默会让真白变得更加孤独。
我明明应该牵起她的手告诉她——我不会让你孤身一人。
欢迎抓虫 被我自己翻的甜到了是怎么回事（
