### ISSUE TITLE
#14776  总有一天会在未来牺牲的毫无价值的人类总数

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#31]
原文：
……それでも、いつか未来で犠牲となる無価値な人類の全体数を考えれば、それは、微々たる犠牲なのかもしれない
原译：
…… 尽管如此，考虑到总有一天会在未来牺牲的毫无价值的人类总数，这也许是微不足道的牺牲。
可能的修改：
……尽管如此，考虑到有许多毫无价值的人类会在将来的某一天牺牲，现在的所付出的代价也许是微不足道的。

**Comment by hiyouga** [comment]
> 现在的所付出的代价也许是微不足道的。

现在所付出的代价也许微不足道。

**Comment by Linrop** [comment]
尽管如此，考虑到将来会牺牲的无价值的人类的总数，这点，也许微不足道。
我倾向保留原词，作者在此并没有用代償

**Comment by hiyouga** [comment]
> 考虑到将来会牺牲的无价值的人类的总数

定语冗长，可以考虑后置或定语改为动词。
