### ISSUE TITLE
#14827 那个不知道相貌和名字已经和陌生人

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#32]
原文：
それに、遠い先祖が――顔も名前も知らないもはや赤の他人同然の誰かが犯した罪によって、どうして、何ら悪に手を染めて いない[俺たち|子孫]が、罰せられなければならないのだろう。
原译：
而且，遥远的祖先——那个不知道相貌和名字已经和陌生人，因为那样的某个人犯下的罪，为什么没有染指任何罪恶的[我们|子 孙]必须受到惩罚呢。
可能的修改：
而且，那个不知道样貌和名字的，已然和陌生人别无二致的遥远的祖先——为什么没有染指任何恶行的[我们|子孙]必须为了这样的人犯下的罪行买单呢。

**Comment by hiyouga** [comment]
【修改建议】

> 而且，那个不知道样貌和名字的，已然和陌生人没有区别的遥远的祖先，为什么没有染指任何恶行的[我们|子孙]必须为了这样的人犯下的罪行买单呢。

而且，那些连样貌和名字都不知道的，已然和陌生人没有区别的老祖先犯下的罪行，为何要让没有染指任何恶行的[我们|子孙]不得不为此买单呢。

**Comment by Sept9th** [comment]
我漏写了破折号，希望重新审阅。

**Comment by Linrop** [comment]
而且，素昧平生的遥远的先祖，为什么，要因为他们的罪行而不得不让～受到惩罚
破折号我看来纯属作者乱用，建议直接化成定语

**Comment by hiyouga** [comment]
> 我漏写了破折号，希望重新审阅。

中文破折号不能这么用，建议去掉破折号分成两个句子。
