### ISSUE TITLE
#14776   他们像是复述似的说

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#33]
原文：
復唱するようにそう言った[イキモノ|誰か]は、空をふと、見上げた。
愿译：
他们像是复述似的说：“谁啊？”突然抬头仰望天空。
可能的修改：
像是复述一般如此说道的[生物|某人]突然抬头看向了天空。

**Comment by Linrop** [comment]
稍作调整
复述似的[生物|某人]忽地抬起头，看向天空
