### ISSUE TITLE
#15276 小黑线 ”担心地看着低着头的我的脸“

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#35]
#15276
原文：うつむいてしまった俺の顔を、心配そうに覗き込んでいた。
原译：担心地看着低着头的我的脸
意见：她担心地看着我低着头的脸

**Comment by Linrop** [comment]
她担心地窥着我垂下的脸
把看着改为窥着，有小心之感，同时更加贴合原文

**Comment by Akatsukiketu** [comment]
她担心地偷瞄着我低下的脸。 窥感觉有点不自然。
