### ISSUE TITLE
#15526 小黑线 “自己的事都保护不住的孩子”

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#37]
#15526
原文：
俺は、ましろ。君のヒーローになりたい。君を苦しめる“悪夢”から救い出したい。自分のことさえ守れない子どもが何を言 ってるんだって、笑われるかもしれないけれど……
原译：
我是，真白。我想成为你的英雄。我想从让你痛苦的“噩梦”中拯救出来。一个连自己的事都保护不住的孩子在说什么，也许会 被嘲笑……
可能的修改：
真白，我啊。我想成为你的英雄。我想把你从让你痛苦的”噩梦“中拯救出来。虽然一个连自己都保护不了的孩子说这些话，也许会被嘲笑......

**Comment by Linrop** [comment]
同意

**Comment by Akatsukiketu** [comment]
“让你”会不会有点冗余，另外中文是不是应该把两句语序换下，先叠甲再宣言呢（

**Comment by Sept9th** [comment]
真白，我啊。我想成为你的英雄，把你从那让你痛苦的”噩梦“中拯救出来。虽然一个连自己都保护不了的孩子说这些话，也许会被嘲笑......
（这里简单去除了冗余内容和重复成分）

下一句是 それが俺の“夢”なんだ。 我个人判断“会被嘲笑”是指这种“梦想”，因此可能会需要将这两句连贯译出？或是对这两句同时进行修改？

**Comment by Akatsukiketu** [comment]
> 真白，我啊。我想成为你的英雄，把你从那让你痛苦的”噩梦“中拯救出来。虽然一个连自己都保护不了的孩子说这些话，也许会被嘲笑...... （这里简单去除了冗余内容和重复成分）
> 
> 下一句是 それが俺の“夢”なんだ。 我个人判断“会被嘲笑”是指这种“梦想”，因此可能会需要将这两句连贯译出？或是对这两句同时进行修改？

根据你所述的 最后“但这就是我的梦想。”结尾如何？因为前面有嘲笑，就最后加个转折？
