### ISSUE TITLE
#15735 小黑线 “没这样说过的孩子”

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#39]
#15735
原文：
自分で口にしておきながらませた子どもだ。つくづくそう思う。そう、思うけど……。
原译：
自己果然是一个没这样说过的孩子啊，我深深地这样想到。

思う可能需要反复一次？第一句也译错了。

**Comment by Linrop** [comment]
原译有大纰漏，此处为“早熟的孩子”
故应译作
虽然要我自己说是个早熟的孩子，我真的这么认为。我真的，但是...

**Comment by hiyouga** [comment]
> 口にしておきながら

等同于

“口にしていたのに”

表示与后面成分是矛盾的关系

故应翻为：

“就算自己那么说，也还是个早熟的孩子。我深悉如此。然而……”

没有前后文，前半句的主语成分还可以进一步润色
