### ISSUE TITLE
#385 共通 “感同身受”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#4]
### 原文

>空腹にしみるなあ。
>しみじみとしてしまう。

### 原译

>好饿啊……
>感同身受。

### 意见

>“しみる”“しみじみ”的意思都是“打心底里觉得”，因而这里的意思应该是“肚子饿的感觉更强烈了”，第二句是再进一步的形容，而非图中之意——老实说，我其实没看懂这个“感同身受”是什么意思。

**Comment by Linrop** [comment]
好饿啊……我深深的感到

**Comment by Akatsukiketu** [comment]
好饿...饥饿感充斥着我的全身。
