### ISSUE TITLE
#15742 我一秒钟都想不到

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#40]
#15742 
原文：
この数日で自分の気持ちを確かめられた。俺は、奏大雅は、君が好きだ……愛してる。君が“隣”にいない人生なんて、そん なの、一秒だって考えられない
原译：
这几天我确定了自己的心情。我，奏大雅，喜欢你…… 我爱你。你不在我身边的生活，我一秒钟都想不到。

一秒钟都想不到有点神秘。用”我完全无法想象你不在我身边的生活“吧。

**Comment by Linrop** [comment]
只对我爱你后面进行修改。
你不在“身边”的生活，我连一秒钟也不能想
意思是一样的

**Comment by hiyouga** [comment]
> この数日で自分の気持ちを確かめられた。

能动语态。”这几天我能梳理清楚自己的想法了。“

> 一秒だって考えられない

我连一刻都无法想象
