### ISSUE TITLE
#15287 小黑线 “就这样，你想要保护这个世界，全部...全部都是为了我，是啊”

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#41]
#15287
原文：……そうまでして君がこの世界を護ろうとしたのは、全部……ぜんぶ、俺のためだった。そうだよね
原译：就这样，你想要保护这个世界，全部...全部都是为了我，是啊
意见：你不惜如此代价（指前面的代偿）保护这个世界，全都....全都是为了我，对吧。

**Comment by Linrop** [comment]
你不惜如此也要拯救这个世界，全部……都是，为了我，对吧
