### ISSUE TITLE
#15289 小黑线 “真白的沉默是超过了语言的回答”

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#42]
#15289
原文：なんだか受け取り方次第では、ひどく自意識過剰な言い方ではあった。しかし、ましろの沈黙が言葉以上の回答だった。
原译：总觉得根据接受方法的不同，说法可能过于自我意识过剩了。但是，真白的沉默是超过了语言的回答。

个人观点这句话意译会更好一些

**Comment by Linrop** [comment]
总觉得如果接受的方法不同，这也许是非常自大的说法，但是，真白的无言胜有言
不清楚语境 暂且如此浅浅意译一下

**Comment by Akatsukiketu** [comment]
会有人觉得，这是极为自大的说法。但是，真白的沉默已经告诉（我）她是认真的了。
思路：第一句直译的话总感觉根据接受方式，那我换个思路，那就是有的人认为，或者是会有人觉得。因为没有语境，敬请指正。
