### ISSUE TITLE
#15294 小黑线 做出了牺牲很多人的选择

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#43]
#15294
原文：……俺はさ。ほんの数人を助けるために、大勢を犠牲にする選択をする。そういうタイプの人間なんだよ
原译：我呢，为了救助仅有的几个人，做出了牺牲很多人的选择。就是作出这种类型的人啊
意见：会作出牺牲大多数人的选择or会选择牺牲大多数人，干脆直接 牺牲多数人拯救少数人算了。。

**Comment by Linrop** [comment]
我啊，就是那种会为了救少数人而选择重大牺牲的人哦
简化了原文
