### ISSUE TITLE
#15307 小黑线 “告诉她，这就是我今晚来这里的原因”

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#44]
#15307
原文：そう伝えることが、今夜俺がここへ来た理由だ。
原译：告诉她，这就是我今晚来这里的原因
意见：你想告诉谁？？

**Comment by Linrop** [comment]
这么说吧，这就是我今晚来这里的理由
原译意义不明

**Comment by hiyouga** [comment]
> 这么说吧，这就是我今晚来这里的理由 原译意义不明

@Linrop 你这个也是错翻，そう伝えること是为了向某人传达某事，本句应该是“我今晚来这里的原因，就是为了能传达这些事。”

**Comment by Akatsukiketu** [comment]
我今晚来这里，就是为了告诉你这些。 和楼上差不多。我觉得把理由原因省略掉也可以。
