### ISSUE TITLE
#12023 然而，（不知）为何

### ISSUE THREAD

**Issue by ricecakey06** [elementary-particle/my-moyu-text#46]
#12023 しかし、なぜだろう。誰もがその[・|王][・|さ][・|ま]のことを憎からず感じていた。
       然而，为何，所有人都没产生对这位[·|王]的憎恨。

**Comment by hiyouga** [comment]
可这是为什么呢。不论是谁都对这位[・|王]怀着一种爱慕的情感。

**Comment by Linrop** [comment]
我觉得应该保留憎恨

**Comment by hiyouga** [comment]
> 我觉得应该保留憎恨

@Linrop 憎からず固定用法，表示好感，好意。这里是“王”应该是说真白

**Comment by Linrop** [comment]
学艺不精了，昨天查的日汉词典，他没给出固定用法的释义。刚刚查了大辞林还真是> > 我觉得应该保留憎恨
> 
> 
> 
> @Linrop 憎からず固定用法，表示好感，好意。这里是“王”应该是说真白
