### ISSUE TITLE
#12074 我，牛B

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#50]
#12074
原文：
『うん、私、すっごい！』
原译：
嗯，我，牛B。

认为还是别保留这玩意了。

**Comment by Akatsukiketu** [comment]
感觉怎么翻都会有点尬x  忘记是哪里的语境了
这么强，不愧是我！  
这么厉害不愧是我！

**Comment by Linrop** [comment]
到我翻的部分了……“嗯，我，真棒！”
