### ISSUE TITLE
#12077 准备仪容

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#51]
#12077 
原文：
鏡を覗き込む。ああでもないこうでもないと格闘する。
原译：
我盯着镜子，准备仪容。

再怎么样，也应该是整理仪容而不是准备...
何况这里也不像是整理的意思。

**Comment by Akatsukiketu** [comment]
应该是在穿服务生衣服的场景？文中意思就是指的自己身上处处不整洁的地方，褶皱之类的？
我对着镜子，将自己身上不得体的地方打理好

**Comment by Linrop** [comment]
同意
