### ISSUE TITLE
#12078 注意到镜子里的自己

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#52]
#12078 
原文：
そこに映る自分の顔にふと気づく。
原译：
终于注意到镜子里的自己。

镜子里自己的脸。

**Comment by Akatsukiketu** [comment]
首先是脸漏了，其次huto是突然 一下子的意思。我突然注意到镜子里自己的脸

**Comment by Linrop** [comment]
当时初翻故意没翻译脸，应该是后文也有脸
我突然注意到镜子中的自己
