### ISSUE TITLE
#12186 忌日和祭日 统一

### ISSUE THREAD

**Issue by ricecakey06** [elementary-particle/my-moyu-text#55]
12186 ハルの命日ということで、心は、頭の中は、どうしたって昔のことで、拭いきれない後悔で、いっぱいになってしまう。
       虽说是小春的祭日，心头，脑海，为什么充斥着对于过去无法擦去的悔恨呢？

**Comment by Akatsukiketu** [comment]
因为是小春的忌日，无法抹去的悔恨和往事种种充斥在我的脑海和心中。
还可以再改自然一点。我一时间也想不到更好的了。

**Comment by Linrop** [comment]
我倾向于保留原文语序，这里我是考虑到文中多次提到的小春の祭，所以用的祭日。我当时对剧情一无所知

**Comment by Akatsukiketu** [comment]
主要是元翻译将过去的事情当做了无法抹去的后悔的定语，我个人认为这两个是并列属性，应该都是充斥自己心灵和大脑的内容。

**Comment by Linrop** [comment]
> 主要是元翻译将过去的事情当做了无法抹去的后悔的定语，我个人认为这两个是并列属性，应该都是充斥自己心灵和大脑的内容。

我的意思是保留先过去再悔恨
