### ISSUE TITLE
#12233 瞑目

### ISSUE THREAD

**Issue by ricecakey06** [elementary-particle/my-moyu-text#57]
12233 目を閉じる。
       瞑目。

**Comment by hiyouga** [comment]
缺主语，联系上下文，xx闭上了眼睛。

**Comment by Linrop** [comment]
此处故意去除主语及简化用词

**Comment by Linrop** [comment]
为了加快语速

**Comment by hiyouga** [comment]
> 为了加快语速

> 瞑目，常喻死而无憾。元·关汉卿《窦娥冤·第四折》：「替你孩儿尽养生送死之礼，我便九泉之下可也瞑目。」比喻人死的时候无所悬念。如：「甘心瞑目」。唐·薛调《无双传》：「我以仙客为托。尔诚许我，瞑目无所恨也。」

不建议乱用中文词汇。
