### ISSUE TITLE
#535 共通 “笑着说”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#6]
### 原文

>もう全部食べちゃったけどね、と笑う俺。

### 原译

>虽然其实已经全部吃掉了呢，我笑着说。

### 意见

>这里可没有“说”，都是心理吐槽。
>“我笑着想”

**Comment by Linrop** [comment]
我笑着想，～

**Comment by mitukichimei** [comment]
已修改
