### ISSUE TITLE
#12243 就连一件事也做不顺手

### ISSUE THREAD

**Issue by ricecakey06** [elementary-particle/my-moyu-text#60]
12243 何も、何ひとつ、上手くいかなかったし、“夢”も“希望”も何もなく……ただただ、生きてる。
       任何事，就连一件事也做不顺手，梦想也好希望也好，一个也没有……就只是活着。

**Comment by ricecakey06** [comment]
这句话有点怪怪的.........

**Comment by Linrop** [comment]
当时犹豫了很久，现在看来
什么都、就连一件事也没做好过
剩下保留
