### ISSUE TITLE
#12275 消费时间

### ISSUE THREAD

**Issue by ricecakey06** [elementary-particle/my-moyu-text#66]
12275 定時にあがったのだ。まだどんなことをして時間を食われてしまおうと、明日の仕事へ支障が出るほどのことではないはずな のに……。
       无论怎样消费时间，我都不能妨碍到明天的工作。

**Comment by Linrop** [comment]
第一句的意思我认为没必要翻译，所以没翻出来
无论怎么消磨时间，应该都不会影响到明天的工作
