### ISSUE TITLE
#15835 只是因为我现在只是想单方面地说话。

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#68]
#15835 
原文：
答えられなかったり、答えたくないことだったら、何も言わなくていいよ。ただ俺が、今は一方的に話していたいだけだから
原译：
如果是不能回答或者不想回答的事情，什么都不用说哦。 只是因为我现在只是想单方面地说话。

**Comment by Linrop** [comment]
只是我现在，想说出来罢了
