### ISSUE TITLE
#15852 爱死那种了

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#69]
#15852 
原文：
特にね。甘いのが、好きだよ。……ミルク味のやつ。好き。愛してる
原译：
尤其是甜的，我喜欢那个……牛奶味的那种，最喜欢了，爱死那种了。

希望能把句子结构统一。

**Comment by Linrop** [comment]
我最，喜欢，甜的……牛奶味，喜欢，好爱
