### ISSUE TITLE
#554 共通 “和大雅”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#7]
### 原文

>また来年も。無事に、大雅がこの日を迎えられますように。

### 原译

>明年也一样。希望能和大雅，平安地迎来这一天。

### 意见

>小黑这句话还是蛮细节的，对象只有大雅一个人——明年，“你”还能迎来这一天，没有把自己放进去。
>图里是臆测加了意思。

**Comment by Linrop** [comment]
希望大雅明年也、无恙地迎来这一天

**Comment by mitukichimei** [comment]
已修改
