### ISSUE TITLE
#15871 “夜之国”可以分为早期和第二阶段。

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#70]
#15871 
原文：
すごくざっくりとした、身も蓋もないような言い方になっちゃうかもだけど……、“夜の国”は、たとえば初期と第二期に別 けられるよね
原译：
我知道这听起来很笼统，但是…… “夜之国”可以分为早期和第二阶段。

**Comment by Linrop** [comment]
问题不大？

**Comment by Linrop** [comment]
建议是？
