### ISSUE TITLE
#15881 继续活下去，成长着——

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#72]
#15881
原文：
更には、あたらしい“夜の国”では終わってしまった命や、死者でさえも、そこで夢見るように生き続けることができるまで に、成長した――
原译：
甚至，在新的“夜之国”，结束的生命，即使是死者，在那里也能像做梦一样继续活下去，成长着——

别的怎么改懒得想了，但是可能需要“活下去，成长下去——”

**Comment by Akatsukiketu** [comment]
甚至新的“夜之国”已经成长到了（后面就一样了） 
把成长提到前面。这里是已经成长了。

**Comment by Linrop** [comment]
补充，在上述修改的基础上，句尾加“的地步”
