### ISSUE TITLE
#15970 现在已经不记得了，关于少年时代淡淡的“恋爱故事”，会像以前——被一样一个一个认真地讲述吗？

### ISSUE THREAD

**Issue by lxuiii** [elementary-particle/my-moyu-text#74]
15970 今やもう覚えていない、過ぎ去りし少年時代の淡い“恋物語”について、これまでみたいに一つひとつ、丁寧に語られるのだ ろうか。
       现在已经不记得了，关于少年时代淡淡的“恋爱故事”，会像以前——被一样一个一个认真地讲述吗？

**Comment by Linrop** [comment]
不知会不会还像从前那样，一一细数那些已淡忘了的逝去少年时代的浅薄的“恋爱故事”呢。
