### ISSUE TITLE
#572 共通 “温暖与甘甜的香气”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#8]
### 原文

>春先の、暖かく、あまやかな香りが鼻先をくすぐる。

### 原译

>浅春的温暖与甘甜的香气，惹得鼻尖微微有些痒。

### 意见

>这里是词看混了。
>“暖かく”和“あまやか”都是形容“香り”的，看词型也看得出嘛。
>最简单的法子，“与”改“又”就行。
>至于香气为什么会温暖，别问我，问雪人。句子上来看就是这样。

**Comment by Linrop** [comment]
非也，意见有误。语法看来此处温暖用来形容春天。议：初春的温暖、甘甜的微风骚弄着鼻尖

**Comment by Linrop** [comment]
此温暖是名词，不可以名词直接修饰名词；况且如君言，初春后面的no将失去主语

**Comment by Sept9th** [comment]
浅春的温暖//与//甘甜的香气
浅春的//温暖与甘甜的香气

**Comment by Akatsukiketu** [comment]
首先暖かく不能做名词，因此不赞成上面的意见，这里应该都是修饰香气的。其次这个形容词可以表达抽象，心灵状态的温暖，所以我觉得根据意见也是可以的，这里给出自己的拙见：初春温暖甘甜的香气，牵动着我的鼻尖。
