### ISSUE TITLE
#16263 没有任何才能就被生下来了难道仅仅因为这一点就是罪吗

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#80]
原文：
『何の才能も持たず産まれた。たったそれだけのことが罪なのかな。こんなふうに、一方的に罰せられなきゃならないほどの ことなのかな』
原译：
“没有任何才能就被生下来了难道仅仅因为这一点就是罪吗？ 难道就应该像现在这样受到惩罚吗？”

**Comment by Akatsukiketu** [comment]
仅仅因为生下来毫无才能就能成为一个人的罪过吗？是必须要这样一直被惩罚下去的罪过吗？
