### ISSUE TITLE
#16368 而是拥有着

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#83]
#16368 
原文：
女の人はまだやさしい心を忘れず壊さず、持っているように最初は思った。
原译：
一开始我觉得女人还没有忘记温柔的心，而是拥有着。

**Comment by Akatsukiketu** [comment]
我一开始觉得女人还没有忘记温柔，心灵并没有崩坏。（雪人复读，不用把拥有带上了）
