### ISSUE TITLE
#16377 正如你所说。只有最初哦

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#85]
#16377 
原文：
やさしい人のように見えたのは、その心をまだ壊されずにいるのかなと思えたのは、そうだね。うん。君の言うとおり。最初 だけだったよ。
原译：
看上去像是个温柔的人，其实是因为她的心还没有被破坏吧。嗯。正如你所说。只有最初哦。

**Comment by Akatsukiketu** [comment]
嗯。正如你所说，我只有一开始那一瞬间觉得她的心灵还没有崩坏，仍旧是个温柔的人。
