### ISSUE TITLE
#16491  哪里都没有在痛苦的时候期待的方便的英雄

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#87]
#16491 
原文：
苦しいときに期待するような都合のいいヒーローはどこにもいないと知った。ここにいるのはいつも自分、ただひとり。
原译：
知道了哪里都没有在痛苦的时候期待的方便的英雄。在这里的总是自己，只有一个人。

**Comment by Akatsukiketu** [comment]
我知道，一遇到困难就会前来帮助的英雄是不存在的。在这里的只有自己，孤身一人。
