### ISSUE TITLE
#16503 还能稍微进入“夜”吧

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#88]
#16503 
原文：
“夜”と現実とを繋ぐことのできる俺と一緒なら大丈夫。まだ少しなら“夜”に這入ることもできるだろう。
原译：
如果和能把“夜”和现实联系在一起的我在一起的话就没问题了。还能稍微进入“夜”吧。

处理一下后一句，前一句似乎没有不绕的写法。

**Comment by Akatsukiketu** [comment]
建议前面也改一下，虽然真白已经不属于“夜”了……但和能连接“夜”与现实的我在一起话就没问题了。还是能短暂地进入“夜”吧。
