### ISSUE TITLE
#11654 共通“迷路的孩子很逊的”

### ISSUE THREAD

**Issue by Kutinana** [elementary-particle/my-moyu-text#9]
### 原文

>大雅も、ともちゃんも、迷子になるのは別に格好悪くないよって言ってくれたけど……

### 原译

>不管是大雅还是小智都对我说迷路的孩子很逊的……

**Comment by elementary-particle** [comment]
建议：虽然大雅和智仁都告诉我迷路也没什么丢脸的

**Comment by Linrop** [comment]
虽然、大雅、和智仁告诉我迷路没什么丢人的。
