### ISSUE TITLE
#15317  “我是钥匙。为了不让“外面”的某人进入这个“夜”的锁的钥匙”

### ISSUE THREAD

**Issue by ExtraordinaryDu** [elementary-particle/my-moyu-text#90]
#15317
原文：……私は“鍵”なんだよ。この“夜”に、“外”の誰かが無闇に入り込んでこないようにするための
原译：我是钥匙。为了不让“外面”的某人进入这个“夜”的锁的钥匙
意见： “外”の誰か：“外面“的人  無闇に：随意

**Comment by Akatsukiketu** [comment]
不是钥匙吧，是锁吧。
我是锁哦，一把为了让“外面”的人不能随意侵入的安全锁。
