### ISSUE TITLE
#17216 你也还很喜欢你吧

### ISSUE THREAD

**Issue by Sept9th** [elementary-particle/my-moyu-text#91]
#17216 
原文：
まだまだあなたも、あなたが大好きなのだろう男の子のことも、よくわからないことだらけだけど……。だけど今は、子猫の “想い”がわかっただけでいいことにした。
原译：
你也还很喜欢你吧，男孩子的事情也有很多不太清楚的地方……但是现在，只要知道了小猫的“想法”就可以了。

**Comment by Akatsukiketu** [comment]
虽然我对你还有你喜欢的男孩子都不大了解…….但是现在，我（后面一样
